// Keep original order + duplicates so the marquee looks identical to before,
// but serve everything locally from /public/images/3d-marquee.
export const marqueeImages = [
  "/images/3d-marquee/marquee-01.png",
  "/images/3d-marquee/marquee-01.png",
  "/images/3d-marquee/marquee-01.png",
  "/images/3d-marquee/marquee-01.png",
  "/images/3d-marquee/marquee-02.png",
  "/images/3d-marquee/marquee-03.png",
  "/images/3d-marquee/marquee-04.png",
  "/images/3d-marquee/marquee-05.png",
  "/images/3d-marquee/marquee-01.png",
  "/images/3d-marquee/marquee-06.png",
  "/images/3d-marquee/marquee-07.png",
  "/images/3d-marquee/marquee-08.png",
  "/images/3d-marquee/marquee-09.png",
  "/images/3d-marquee/marquee-10.webp",
  "/images/3d-marquee/marquee-11.png",
  "/images/3d-marquee/marquee-12.png",
  "/images/3d-marquee/marquee-13.png",
  "/images/3d-marquee/marquee-10.webp",
  "/images/3d-marquee/marquee-13.png",
  "/images/3d-marquee/marquee-12.png",
  "/images/3d-marquee/marquee-14.jpg",
  "/images/3d-marquee/marquee-13.png",
  "/images/3d-marquee/marquee-15.jpg",
  "/images/3d-marquee/marquee-04.png",
  "/images/3d-marquee/marquee-15.jpg",
  "/images/3d-marquee/marquee-04.png",
  "/images/3d-marquee/marquee-07.png",
];
